version: "2"
services:
  node:
    image: "mryan21/gravelmap:latest"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    expose:
      - "80"
    command: "node server.js"
