name: Staging Docker Image CI

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build the Docker image
        run: docker build . --file Dockerfile --tag mryan21/gravelmap:staging
      -
        name: Push to docker registry
        run: docker push mryan21/gravelmap:staging

  # deploy:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Deploy to Docker 
  #     uses: wshihadeh/docker-deployment-action@v1
  #     with:
  #       remote_docker_host: civo@212.2.244.229
  #       ssh_private_key: ${{ secrets.CIVO_SSH_PRIVATE_KEY }}
  #       ssh_public_key: ${{ secrets.CIVO_SSH_PUBLIC_KEY }}
  #       deployment_mode: docker-compose
  #       deploy_path: /home/civo/gravel-staging
  #       stack_file_name: docker-compose.yaml
  #       keep_files: 5
  #       pull_images_first: true
  #       args: up -d
  #       pre_deployment_command_args: sudo su
